stages:
  - test

variables:
  NODE_ENV: test

.test_template: &test_definition
  stage: test
  before_script:
    - npm config set cache .npm --global
    - npm install --no-audit
  script:
    - npm test
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .npm/
      - node_modules/

test-node11:
  <<: *test_definition
  image: node:11

test-node-lts:
  <<: *test_definition
  image: node:lts

test-node-latest:
  <<: *test_definition
  image: node:latest
  script:
    - npm audit
    - npm test
